/**
 * Датасет распределения заявок по закупщикам — пересчитан из БД (одноразовый срез).
 *
 * Отбор: заявки в статус-группах «Заявка у закупщика», «Договор в работе»,
 * «Договор подписан», у которых ГОД даты завершения = 2026. Дата завершения —
 * max(completionDate) по согласованиям закупки, если все согласования завершены;
 * если даты завершения нет — берётся год даты создания заявки. Итого 176 заявок.
 *
 * `category` — тематическая категория статьи расходов (определена вручную).
 * `proposedPurchaser` — предполагаемый закупщик (владелец категории), для балансировки
 * с учётом нового, ещё не представленного закупщика («Новый»).
 * `currentPurchaser` — закупщик, который ведёт заявку сейчас.
 * Бюджет `amount` — в валюте заявки (в осн. СУМ); в дашборде переводится в млн.
 */

export interface PurchaserRequestRow {
  /** Номер заявки */
  number: string;
  /** Наименование закупки */
  name: string;
  /** Предмет заявки */
  subject: string;
  /** Статья расходов */
  expenseItem: string;
  /** Тематическая категория (определена вручную) */
  category: string;
  /** Бюджет в валюте заявки */
  amount: number;
  /** Валюта */
  currency: string;
  /** Сложность (баллы) */
  complexity: number;
  /** Ведущий закупщик (текущий) */
  currentPurchaser: string;
  /** Предполагаемый закупщик (владелец категории) */
  proposedPurchaser: string;
  /** true — год определён по дате завершения, false — по дате создания */
  byCompletion: boolean;
}

/** Категории и их владельцы (предполагаемые закупщики). */
export const CATEGORY_OWNERS: Record<string, { owner: string; isNew?: boolean }> = {
  'Ремонт, стройка, эксплуатация': { owner: 'Абдулазиз' },
  'Транспорт, страхование, персонал': { owner: 'Шакирова' },
  'Основные средства, оборудование, маркетинг': { owner: 'Исакова' },
  'Хозобеспечение / АХО': { owner: 'Новый', isNew: true },
};

export const PURCHASER_DISTRIBUTION_REQUESTS: PurchaserRequestRow[] = [
  {
    number: '0000-0000037753',
    name: 'APPRAISE LAB',
    subject: '—',
    expenseItem: 'Лицензии и программные права',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 19000,
    currency: 'USD',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000046187',
    name: 'Uzum E-com IT Olympiad',
    subject: '—',
    expenseItem: 'Мерч',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 31342080,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000035402',
    name: 'Акустические кресла в офис',
    subject: '—',
    expenseItem: 'Приобретение мебели',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 30000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000035296',
    name: 'Беспроводные кольцевые сканеры',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 260000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000049258',
    name: 'Бордюр дорожный -10 шт, бордюр конус- 20 шт на склад ФФ.',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 7500000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000047043',
    name: 'Водные вентиляторы на склад 15 шт',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 25000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000035849',
    name: 'Деревянные панели в офис',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 5360000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000035761',
    name: 'Диван в офис',
    subject: '—',
    expenseItem: 'Приобретение мебели',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 3000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000036178',
    name: 'ЗУЕИ "SMARTCAST" MCHJ',
    subject: '—',
    expenseItem: 'Лицензии и программные права',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 68100000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000044265',
    name: 'ЗУЕИ ООО RESEARCH GROUP CA',
    subject: '—',
    expenseItem: 'Маркетинговые исследования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 85120000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000037906',
    name: 'Закуп терминалов',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 1002300000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000047804',
    name: 'Закупка POS-терминалов моделей Lane-3600 и PAX A35',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 3860841000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000045913',
    name: 'Закупка POS-терминалов моделей Lane-3600 и PAX A35',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 2573894000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000042276',
    name: 'Закупка коробов из гофрокартона для ПВЗ',
    subject: '—',
    expenseItem: 'Средства хранения и транспортировки товаров/заказов',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 146768832,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000035785',
    name: 'Закупка коробов из гофрокартона для ПВЗ',
    subject: '—',
    expenseItem: 'Средства хранения и транспортировки товаров/заказов',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 184100000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000042405',
    name: 'Закупка металлических стеллажей для хранения заказов в пунктах выдачи заказов (ПВЗ).',
    subject: '—',
    expenseItem: 'Приобретение мебели',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 415744000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000033939',
    name: 'Закупка металлических стеллажей для хранения заказов в пунктах выдачи заказов (ПВЗ).',
    subject: '—',
    expenseItem: 'Приобретение мебели',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 2086500000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000045887',
    name: 'Закупка плат жных терминалов SmartOne Bank Pro (2шт)',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 4600000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000048077',
    name: 'Заявка  (ДС 1 к договору NISHON GROUP PRODUCT MCHJ 398 от 11.02.2026)',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 98586000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000040020',
    name: 'Заявка на ЗП  турникета и монтажных услуг',
    subject: '—',
    expenseItem: 'Услуги ИТ',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 31445344,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000034213',
    name: 'Заявка на ЗП Баркодеров на 2026 год',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 250000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000047979',
    name: 'Заявка на ЗП, коммутаторы и блоки питания',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 65000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000040737',
    name: 'Заявка на Коммутаторы и блоки питания',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 70000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000041727',
    name: 'Заявка на Печать',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 7000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000048056',
    name: 'Заявка на авто-шины',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 260400000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000041726',
    name: 'Заявка на тендер',
    subject: '—',
    expenseItem: 'Услуги ИТ',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 36749793,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000036618',
    name: 'Звукоизоляционные кабины',
    subject: '—',
    expenseItem: 'Приобретение мебели',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 182500000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000048706',
    name: 'Зеркальные конструкции',
    subject: '—',
    expenseItem: 'Брендинг: creative, celebrity, production',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 199752000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000039896',
    name: 'ЗуЕИ OOO UNITEL',
    subject: '—',
    expenseItem: 'SMS-информирование',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 119280000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000049383',
    name: 'Кресло для ПВЗ -20 шт, офисные кресла -10 шт.',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 17360000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000048762',
    name: 'Кухонный гарнитур в новый офис.',
    subject: '—',
    expenseItem: 'Приобретение мебели',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 42000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000040238',
    name: 'Мерч Iron Cup',
    subject: '—',
    expenseItem: 'Мерч',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 110000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000035302',
    name: 'Мобильная погрузочка эстакада',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 60000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000035215',
    name: 'Модернизация системы технологического видеонаблюдения на складах Узум Маркет',
    subject: '—',
    expenseItem: 'Услуги ИТ',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 100000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000047475',
    name: 'На поставку туннельной автоматической термоусадочной упаковочной линии Модель GS-FQB-450 на склад.',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 68000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000036261',
    name: 'Наклонные стеллажи',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 626229517,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000040270',
    name: 'ОГЭ: ОПН-35/41  - 6 шт.',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 36000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000036200',
    name: 'ООО «EFFEKTIV SINERGIYA»  06/26',
    subject: '—',
    expenseItem: 'Мерч',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 9526720,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000036239',
    name: 'ООО «MELAGRANA PRODUCTIONS»  14',
    subject: '—',
    expenseItem: 'Мерч',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 4000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000035420',
    name: 'Ограничитель перенапряжений ОПН-ЛИр3-35/41=10/650 (II) УХЛ1  (10шт.)',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 60000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000036715',
    name: 'Организация BTL/OOH-активации под ключ',
    subject: '—',
    expenseItem: 'Соушал: контент (LIVE, лента, студия, SMM), Охватные блогеры / посевы, Media',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 164565899,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000046398',
    name: 'Офис: доукомплектовка СКУД',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 70000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000042211',
    name: 'Офисные кресла',
    subject: '—',
    expenseItem: 'Приобретение мебели',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 519500000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000036121',
    name: 'Паллетные ограждения',
    subject: '—',
    expenseItem: 'Средства хранения и транспортировки товаров/заказов',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 260801402,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000042073',
    name: 'Поддоны деревянные',
    subject: '—',
    expenseItem: 'Средства хранения и транспортировки товаров/заказов',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 39580800,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000043767',
    name: 'Покупка плоттера',
    subject: '—',
    expenseItem: 'Приобретение орг техники',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 25000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000046043',
    name: 'Покупка электрического ричтрака 12,5 м.',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 397600000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000032540',
    name: 'Предоставление услуг мониторинга ключевых позиций в поисковых системах',
    subject: '—',
    expenseItem: 'Медиабаинг: Retargeting',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 5000,
    currency: 'USD',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000037908',
    name: 'Приобретение ричтрака',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 612627212,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000044386',
    name: 'Рич трак для склада.',
    subject: '—',
    expenseItem: 'Аренда прочая',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 213500000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000035304',
    name: 'Роллкейдж',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 425362732,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000048132',
    name: 'СЗ - оснащения нового офиса E-com по адресу: г. Ташкент, ул. Богибустoн 3А',
    subject: '—',
    expenseItem: 'Услуги ИТ',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 320523728,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000040160',
    name: 'СКИЛАЗ ЗП',
    subject: '—',
    expenseItem: 'Лицензии и программные права',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 5525000,
    currency: 'RUB',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000037312',
    name: 'ТЗ СКУД и CCTV, модернизация для КД (годовые объ мы на 2026 год)',
    subject: '—',
    expenseItem: 'Услуги ИТ',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 200000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000047030',
    name: 'ТЗ на мебель для ПВЗ',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 1220654800,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000039025',
    name: 'Тарные ящики МАРТ',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 2914912000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000035299',
    name: 'Тележки покупательские',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 276889800,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000035297',
    name: 'Телефоны на базе Android.',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 247000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000037917',
    name: 'Тендер внутрискладская тара',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 2000000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000037140',
    name: 'Тендер по поиску поставщика для приобретения рохлей',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 120000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000042087',
    name: 'Тендер поддоны 2026-2027',
    subject: '—',
    expenseItem: 'Средства хранения и транспортировки товаров/заказов',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 420000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000040320',
    name: 'Термологгеры на склад',
    subject: '—',
    expenseItem: 'Списание малоценного оборудования',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 70000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000031816',
    name: 'Услуги по полиграфии и производству рекламных материалов',
    subject: '—',
    expenseItem: 'Брендинг: creative, celebrity, production',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 2451676000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000047969',
    name: 'Услуги по полиграфии рекламных материалов',
    subject: '—',
    expenseItem: 'Медиабаинг: наружка (outdoor, indoor, transit)',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 2398182000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Исакова',
    byCompletion: false,
  },
  {
    number: '0000-0000036094',
    name: 'ФФЦ: Контейнер 40 футов - 2шт.',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 24000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000040952',
    name: 'Фурнитура для тарных ящиков',
    subject: '—',
    expenseItem: 'Приобретение прочих ОС',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 81664000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000041135',
    name: 'аренда рич трака',
    subject: '—',
    expenseItem: 'Аренда прочая',
    category: 'Основные средства, оборудование, маркетинг',
    amount: 105000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Исакова',
    byCompletion: true,
  },
  {
    number: '0000-0000046041',
    name: 'Закуп комплектующих для ТСД',
    subject: '—',
    expenseItem: 'Материалы и запчасти на ремонт',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 122191524,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000038958',
    name: 'Закуп складской технике',
    subject: '—',
    expenseItem: 'Приобретение спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 25000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000046391',
    name: 'Заявка на ЗП на ж сткие диски и NVR',
    subject: '—',
    expenseItem: 'Материалы и запчасти на ремонт',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 35000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000036362',
    name: 'Заявка на ремонт трансформатора',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 200000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000035560',
    name: 'Навесы из металоконструкции в офис',
    subject: '—',
    expenseItem: 'Ремонт зданий и сооружений',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 23100000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000038260',
    name: 'ПВЗ: счетчики воды - 10шт.',
    subject: '—',
    expenseItem: 'Ремонт ПВЗ',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 25000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000044264',
    name: 'Ремонт и замена витражей и стеклопакетов в ПВЗ',
    subject: '—',
    expenseItem: 'Ремонт ПВЗ',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 200000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000043025',
    name: 'Склад Сергели: Компрессоры  для VRF системы - 4шт.',
    subject: '—',
    expenseItem: 'Материалы и запчасти на ремонт',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 48000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000038087',
    name: 'Счетчик электроэнергии - 200шт.',
    subject: '—',
    expenseItem: 'Ремонт ПВЗ',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 230000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000039870',
    name: 'Счетчики эл.эн., щиты учета, автоматические выключатели',
    subject: '—',
    expenseItem: 'Ремонт ПВЗ',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 66000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000045979',
    name: 'ТЗ на СМР',
    subject: '—',
    expenseItem: 'Ремонт ПВЗ',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 2000000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000041511',
    name: 'ТЗ на ТО ДГУ (Нилуфар 77/7; Кичик Бешагач 132А; Малая кольцевая 54)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 200000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000035614',
    name: 'ТЗ на ТО ТП, ДГУ и линий передач (склад Сергели)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 198000000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000044282',
    name: 'ТЗ на ТО и контроль конденсаторных компенсирующих установок реактивной мощности и приборов учета',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 60000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000041444',
    name: 'ТЗ на ТО и ремонт кондиционеров в ПВЗ',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 540000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000035612',
    name: 'ТЗ на ТО и ремонт систем отопления, кондиционирования и котельной (Нилюфар 77/7)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 319000000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000046280',
    name: 'ТЗ на ТО и ремонт систем пожарной сигнализации, автоматического оповещения о пожаре, автоматической системы пожаротушения (ФФЦ)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 468000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000043024',
    name: 'ТЗ на ТО насосной станции внутри площадочной системы К-1 и КНС (ФФЦ)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 486000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000048708',
    name: 'ТЗ на закупку приточно-очистительных вентиляционных установок (бризеров). Офис - Богибустон 3А',
    subject: '—',
    expenseItem: 'Капитальные ремонт зданий и сооружений',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 430000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000039926',
    name: 'ТЗ на изготовление и установку рекламных конструкций',
    subject: '—',
    expenseItem: 'Ремонт ПВЗ',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 600000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000041512',
    name: 'ТЗ на обслуживание складской техники (ричтраки, кары, штабелеры)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 100000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000034937',
    name: 'ТЗ на объедuненuя пульmов дuспеmчерuзацuu устройство АПС и СОУЭ (склад Сергели здания  7,18,19,20)',
    subject: '—',
    expenseItem: 'Ремонт зданий и сооружений',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 78400000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000036250',
    name: 'ТЗ на проведение проверки фронтального стеллажного оборудования (ФФЦ, Нилуфар 77.7)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 150000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000047020',
    name: 'ТЗ на разраб. проектной документации по оснащению серверных помещений системами противопожарной защиты и инж. сист.',
    subject: '—',
    expenseItem: 'Капитальные ремонт зданий и сооружений',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 24192000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000047589',
    name: 'ТЗ на реализацию и оснащение помещений системами противопожарной защиты и инженерными системами под ключ',
    subject: '—',
    expenseItem: 'Капитальные ремонт зданий и сооружений',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 874192000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000036592',
    name: 'ТЗ на тех. обслуживание и ремонт ОВиК на складах ФФЦ (Ханабад 2/2) и Сергели (Нилуфар 77/7)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 1440000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000036592',
    name: 'ТЗ на тех. обслуживание и ремонт ОВиК на складах ФФЦ (Ханабад 2/2) и Сергели (Нилуфар 77/7)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 1440000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000040722',
    name: 'ТЗ на тех. обслуживание эл. установок 35кВ, 10кВ, 0,4кВ (Ханабад 2/2, Нилуфар 77/7, Кичик Бешагач 132А, Малая Кольцевая 54)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 300000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000036202',
    name: 'ТЗ на тех. обслуживание эл. установок 35кВ, 10кВ, 0,4кВ и ДГУ (Ханабад 2/2, Нилуфар 77/7, Кичик Бешагач 132А, Малая Кольцевая 54)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 500000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000035303',
    name: 'ТЗ на техническое обслуживание ДГУ 750 кВА (офис)',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 94080000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000044213',
    name: 'ТЗ на установку АПС в ПВЗ',
    subject: '—',
    expenseItem: 'Ремонт ПВЗ',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 3208000037,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000043761',
    name: 'ТЗ на устройство всесезонного ангара каркасного типа (Ханабад 2/2)',
    subject: '—',
    expenseItem: 'Капитальное строительство',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 531000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000033896',
    name: 'ТЗ на устройство наружных сетей канализации и монтаж санитарного модуля (склад Сергели)',
    subject: '—',
    expenseItem: 'Капитальное строительство',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 103535521,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000048491',
    name: 'ТЗ на устройство санитарного узла на 2 посадочных места (ФФЦ)',
    subject: '—',
    expenseItem: 'Капитальное строительство',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 50000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000036001',
    name: 'ТЗ нанесение горизонтальной дорожной разметки (ФФЦ)',
    subject: '—',
    expenseItem: 'Ремонт зданий и сооружений',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 50000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000036003',
    name: 'Уход за декоративными цветами',
    subject: '—',
    expenseItem: 'Содержание и эксплуатация офиса',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 110000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000048777',
    name: 'ФФЦ: Извещатель пожарный дымовой оптико-электронный адресно-аналоговый ИП 212-64-R3   - 1500шт.',
    subject: '—',
    expenseItem: 'Материалы и запчасти на ремонт',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 272970000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000039875',
    name: 'ФФЦ: ТЗ на ТО и ремонт систем пожарной сигнализации, авт. оповещения о пожаре, автоматической системы пожаротушения ФФЦ',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 540000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000043882',
    name: 'ФФЦ: выравние фронтальных стеллажей, замена отбойников',
    subject: '—',
    expenseItem: 'Ремонт и обслуживание спец.техники и оборудования',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 106948800,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000043230',
    name: 'ФФЦ: заявка на трансформаторы 3 шт.',
    subject: '—',
    expenseItem: 'Материалы и запчасти на ремонт',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 60000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000048734',
    name: 'ФФЦ:пожарный прибор SONAR SPM-C20085-AR',
    subject: '—',
    expenseItem: 'Материалы и запчасти на ремонт',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 156800000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000044006',
    name: 'Химчистка',
    subject: '—',
    expenseItem: 'Содержание и эксплуатация офиса',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 200000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000046513',
    name: 'Химчистка ковров в офисе',
    subject: '—',
    expenseItem: 'Содержание и эксплуатация офиса',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 838000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Кандалинцева',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000038088',
    name: 'Щит учета - 200шт.; автоматический выключатель - 200шт.',
    subject: '—',
    expenseItem: 'Ремонт ПВЗ',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 40000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: true,
  },
  {
    number: '0000-0000037155',
    name: 'Щиты учета - 35шт.; счетчики электроэнергии - 30 шт.',
    subject: '—',
    expenseItem: 'Ремонт ПВЗ',
    category: 'Ремонт, стройка, эксплуатация',
    amount: 40450000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Абдулазиз',
    byCompletion: false,
  },
  {
    number: '0000-0000040590',
    name: 'DevOpsDays CЗ',
    subject: '—',
    expenseItem: 'Обучение и конференции',
    category: 'Транспорт, страхование, персонал',
    amount: 24540000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000047018',
    name: 'Exode Tech',
    subject: '—',
    expenseItem: 'Обучение и конференции',
    category: 'Транспорт, страхование, персонал',
    amount: 139800000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000045859',
    name: 'Гостиничный комплекс Edelweiss',
    subject: '—',
    expenseItem: 'Тимбилдинг',
    category: 'Транспорт, страхование, персонал',
    amount: 135261600,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000042963',
    name: 'ЕВМ   Организация и проведение деловой игры "Шелковый путь"',
    subject: '—',
    expenseItem: 'Тимбилдинг',
    category: 'Транспорт, страхование, персонал',
    amount: 902000,
    currency: 'RUB',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000039110',
    name: 'Закуп раций',
    subject: '—',
    expenseItem: 'Прочие операционные расходы',
    category: 'Транспорт, страхование, персонал',
    amount: 15200000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000038966',
    name: 'Закупка мед- принадлежностей',
    subject: '—',
    expenseItem: 'Медицинские услуги',
    category: 'Транспорт, страхование, персонал',
    amount: 9500000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000041305',
    name: 'Заявка на Газели!!!',
    subject: '—',
    expenseItem: 'Приобретение транспортных средств',
    category: 'Транспорт, страхование, персонал',
    amount: 1645500000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000037606',
    name: 'Заявка на ЗП!',
    subject: '—',
    expenseItem: 'Приобретение транспортных средств',
    category: 'Транспорт, страхование, персонал',
    amount: 19228000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000039745',
    name: 'Заявка на Осаго',
    subject: '—',
    expenseItem: 'Страхование',
    category: 'Транспорт, страхование, персонал',
    amount: 2688000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000043464',
    name: 'Заявка на Осаго',
    subject: '—',
    expenseItem: 'Страхование авто (ОСАГО)',
    category: 'Транспорт, страхование, персонал',
    amount: 5376000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000043696',
    name: 'Заявка на Страхование автотранспорта по тарифу КАСКО 2026, Обязательное страхование гражданской ответственности владельцев транспортных средств 2026',
    subject: '—',
    expenseItem: 'Страхование',
    category: 'Транспорт, страхование, персонал',
    amount: 1721600328,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000034154',
    name: 'Заявка на Шины',
    subject: '—',
    expenseItem: 'Транспортные расходы',
    category: 'Транспорт, страхование, персонал',
    amount: 100000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000046396',
    name: 'Заявка на закуп',
    subject: '—',
    expenseItem: 'Медицинские услуги',
    category: 'Транспорт, страхование, персонал',
    amount: 50000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000036607',
    name: 'Заявка на закуп Газелей!',
    subject: '—',
    expenseItem: 'Приобретение транспортных средств',
    category: 'Транспорт, страхование, персонал',
    amount: 2235600000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000037408',
    name: 'Заявка на закуп Газелей!!!',
    subject: '—',
    expenseItem: 'Приобретение транспортных средств',
    category: 'Транспорт, страхование, персонал',
    amount: 2235600000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000038826',
    name: 'Заявка на закуп защитного кожуха для ИПР',
    subject: '—',
    expenseItem: 'Прочие операционные расходы',
    category: 'Транспорт, страхование, персонал',
    amount: 21000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000040252',
    name: 'Заявка на поиск КА',
    subject: '—',
    expenseItem: 'Медицинские услуги',
    category: 'Транспорт, страхование, персонал',
    amount: 1,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000043957',
    name: 'Заявка на поиск мед-услуг г. Бухары',
    subject: '—',
    expenseItem: 'Медицинские услуги',
    category: 'Транспорт, страхование, персонал',
    amount: 8000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000048936',
    name: 'Заявка на покупку авто',
    subject: '—',
    expenseItem: 'Приобретение транспортных средств',
    category: 'Транспорт, страхование, персонал',
    amount: 21804000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000035929',
    name: 'Заявка на страхование',
    subject: '—',
    expenseItem: 'Страхование',
    category: 'Транспорт, страхование, персонал',
    amount: 1344000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000043261',
    name: 'Заявка на тендер, Заключение договора на поиск поставщика outsourcing',
    subject: '—',
    expenseItem: 'Найм транспорта',
    category: 'Транспорт, страхование, персонал',
    amount: 670200000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000048147',
    name: 'Заявка, Проведение тендера по выбору поставщика услуг по техническому обслуживанию и ремонту ТС',
    subject: '—',
    expenseItem: 'Обслуживание транспортных средств',
    category: 'Транспорт, страхование, персонал',
    amount: 1,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000036488',
    name: 'Заявка, поиск КА',
    subject: '—',
    expenseItem: 'Найм транспорта',
    category: 'Транспорт, страхование, персонал',
    amount: 500000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000042131',
    name: 'Кейтеринг MARKOOM OUT-SOURCE',
    subject: '—',
    expenseItem: 'Корпоративные мероприятия',
    category: 'Транспорт, страхование, персонал',
    amount: 62670720,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000040974',
    name: 'Навруз офис',
    subject: '—',
    expenseItem: 'Корпоративные мероприятия',
    category: 'Транспорт, страхование, персонал',
    amount: 145800000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000040975',
    name: 'Навруз склад',
    subject: '—',
    expenseItem: 'Корпоративные мероприятия',
    category: 'Транспорт, страхование, персонал',
    amount: 130200000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000039820',
    name: 'ОГЭ: антискалант, картридж, гипохлорид натрия',
    subject: '—',
    expenseItem: 'Прочие операционные расходы',
    category: 'Транспорт, страхование, персонал',
    amount: 20850000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000045861',
    name: 'ООО Tехrtораrk обучение',
    subject: '—',
    expenseItem: 'Обучение и конференции',
    category: 'Транспорт, страхование, персонал',
    amount: 26800000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000048413',
    name: 'Обязательное страхование гражданской ответственности работодателя',
    subject: '—',
    expenseItem: 'ОСГОР (обязательное страхование)',
    category: 'Транспорт, страхование, персонал',
    amount: 140627389,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000034691',
    name: 'Оказание медицинских услуг по содержанию медицинского пункта',
    subject: '—',
    expenseItem: 'Прочие операционные расходы',
    category: 'Транспорт, страхование, персонал',
    amount: 35000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000041972',
    name: 'ПВЗ: фейскэп, пленка для стола проверки, заглушки для стола',
    subject: '—',
    expenseItem: 'Прочие операционные расходы',
    category: 'Транспорт, страхование, персонал',
    amount: 38422368,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Шакирова',
    byCompletion: false,
  },
  {
    number: '0000-0000048547',
    name: 'Служебная записка - PRIMER BUS',
    subject: '—',
    expenseItem: 'Прочие расходы на персонал',
    category: 'Транспорт, страхование, персонал',
    amount: 312480000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Шакирова',
    byCompletion: true,
  },
  {
    number: '0000-0000048935',
    name: 'Ахма ИЮЛЬ',
    subject: '—',
    expenseItem: 'Хозяйственные товары',
    category: 'Хозобеспечение / АХО',
    amount: 10000000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Новый',
    byCompletion: false,
  },
  {
    number: '0000-0000043477',
    name: 'Вода 0,33 для офиса и склада Годовая заявка',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 261676800,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000046013',
    name: 'Вода в капсулах (увеличение суммы договора)',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 330000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000046313',
    name: 'Годова заявка на молоко 2026-2027 г.',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 340200000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000046310',
    name: 'Годовая заявка на моющие средства с 2026 -2027 год.',
    subject: '—',
    expenseItem: 'Хозяйственные товары',
    category: 'Хозобеспечение / АХО',
    amount: 75600000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000044906',
    name: 'Годовая заявка на скотч- 84 000.',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 1386000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000035350',
    name: 'Инкас мешки на ПВЗ',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 100000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000034642',
    name: 'Кур паки январь (альфа)',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 125994000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Новый',
    byCompletion: false,
  },
  {
    number: '0000-0000036650',
    name: 'Лекарство для сотрудников потребность на 1 год.',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 238019796,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000035945',
    name: 'Лекарство и средство личной гигиены.',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 5359558,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Новый',
    byCompletion: false,
  },
  {
    number: '0000-0000029077',
    name: 'Мешки полипропиленновые 55*95 на 12 месяцев',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 168000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000023125',
    name: 'Мусорные пакеты на 30л-120 л на 12 месяцев.',
    subject: '—',
    expenseItem: 'Хозяйственные товары',
    category: 'Хозобеспечение / АХО',
    amount: 500000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000045657',
    name: 'Пакет майка с логотипом.',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 1,
    currency: 'СУМ',
    complexity: 1,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000022985',
    name: 'Пакеты майка на 12 месяцев.',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 1200000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000035468',
    name: 'Поиск нового КА на поставку сиропов для кофе',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 23000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000040826',
    name: 'Стрейч пленка на май',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 1105000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000039048',
    name: 'Тендер БОПП пакеты',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 220000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000033990',
    name: 'Тендер на инкасс мешки',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 766343000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000033170',
    name: 'Тендер на одноразовую посуду',
    subject: '—',
    expenseItem: 'Хозяйственные товары',
    category: 'Хозобеспечение / АХО',
    amount: 400000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000041824',
    name: 'Тендер пломбы',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 400000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000036842',
    name: 'Тендер по поиску поставщика воздушно пупырчатой пленки',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 150000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000036667',
    name: 'Тендер по поиску поставщика стрейч пленки',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 10000000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000036850',
    name: 'Тендер по поиску поставщика термоэтикетки',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 1800000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Шакирова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000042412',
    name: 'Тендер униформа',
    subject: '—',
    expenseItem: 'Униформа',
    category: 'Хозобеспечение / АХО',
    amount: 1800000000,
    currency: 'СУМ',
    complexity: 4,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000040587',
    name: 'Термоэтикетка белая',
    subject: '—',
    expenseItem: 'Расходные материалы для заказов',
    category: 'Хозобеспечение / АХО',
    amount: 155833440,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000043034',
    name: 'Торк мыло и салфетки годовая',
    subject: '—',
    expenseItem: 'Хозяйственные товары',
    category: 'Хозобеспечение / АХО',
    amount: 403920000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Исакова',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000041607',
    name: 'Униформа фиолетовые футболки',
    subject: '—',
    expenseItem: 'Униформа',
    category: 'Хозобеспечение / АХО',
    amount: 19800000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Новый',
    byCompletion: false,
  },
  {
    number: '0000-0000036419',
    name: 'Чай тоза январь',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 8100000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Новый',
    byCompletion: false,
  },
  {
    number: '0000-0000043793',
    name: 'Штаны для склада',
    subject: '—',
    expenseItem: 'Униформа',
    category: 'Хозобеспечение / АХО',
    amount: 110000000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000036111',
    name: 'Штаны черные для склада',
    subject: '—',
    expenseItem: 'Униформа',
    category: 'Хозобеспечение / АХО',
    amount: 157500000,
    currency: 'СУМ',
    complexity: 3,
    currentPurchaser: 'Абдулазиз',
    proposedPurchaser: 'Новый',
    byCompletion: true,
  },
  {
    number: '0000-0000046610',
    name: 'пепси июнь',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 55000000,
    currency: 'СУМ',
    complexity: 0,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Новый',
    byCompletion: false,
  },
  {
    number: '0000-0000047720',
    name: 'пломбы для инкассации d10',
    subject: '—',
    expenseItem: 'Списание тмц на операционные нужды',
    category: 'Хозобеспечение / АХО',
    amount: 10000000,
    currency: 'СУМ',
    complexity: 2,
    currentPurchaser: 'Киреева',
    proposedPurchaser: 'Новый',
    byCompletion: false,
  },
];
